# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  buildAndroid:
  #   # The type of runner that the job will run on
     runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
      
       - name: Retrieve Cache
         uses: actions/cache@v4
         with:
           path: |
             export/release/android/haxe
             export/release/android/obj
           key: ${{ runner.os }}-cache

       - uses: krdlab/setup-haxe@master
         with:
           haxe-version: 4.3.7
      
       - name: Setup Java JDK
         uses: actions/setup-java@v2
         with:
            distribution: 'temurin'
            java-version: '21'

       - name: Setup Android NDK
         uses: nttld/setup-ndk@v1
         id: setup-ndk
         with:
            ndk-version: r28c
      
        # Runs a set of commands using the runners shell
       - name: Install Haxelib
         run: |
            sudo apt-get install libvlc-dev
            sudo apt-get install libvlccore-dev
            haxelib setup ~/haxelib
            haxelib install flixel-addons --quiet
            haxelib install openfl --quiet
            haxelib install flixel 5.5.0 --quiet
            haxelib install format --quiet
            haxelib install hxcpp > /dev/null --quiet
            haxelib install hmm --quiet
            haxelib run hmm install --quiet
            haxelib run lime config ANDROID_SDK $ANDROID_HOME
            haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
            haxelib run lime config JAVA_HOME $JAVA_HOME
            haxelib run lime config ANDROID_SETUP true

       - name: Create Version Tag
         run: echo "${{github.run_id}}" > VERSION
       - name: clean android
         run: lime clean Project.xml android
       - name: Compile
         run: haxelib run lime build Project.xml android -clean -final -D -DHXCPP_M64 --app-version="4.0.0-${{ github.run_id}}"        
       - name: Publish Artifact
         uses: actions/upload-artifact@v4
         with:
           name: androidBuild
           path: 'export/release/android/bin/app/build/outputs/apk'
           smh: code signing shit
  buildiOS:
     runs-on: macos-latest

     steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: Retrieve Cache
          uses: actions/cache@v4
          with:
            path: |
              export/release/ios/haxe
              export/release/ios/obj
            key: ${{ runner.os }}-cache

        - uses: krdlab/setup-haxe@master
          with:
            haxe-version: 4.3.7
        # Runs a set of commands using the runners shell
        - name: Install Haxelib
          run: |
            haxelib setup ~/haxelib
            haxelib install flixel-addons --quiet
            haxelib install openfl --quiet
            haxelib install flixel 5.5.0 --quiet
            haxelib install format --quiet
            haxelib install hxcpp > /dev/null --quiet
            haxelib install hmm --quiet
            haxelib run hmm install --quiet
        - name: Create Version Tag
          run: echo "${{github.run_id}}" > VERSION
        - name: clean iOS
          run: haxelib run lime clean ios
        - name: hxcpp rebuild ig
          run: haxelib run lime rebuild hxcpp
        - name: Compile
          run: haxelib run lime build ios -final -nosign -D -clean -v -Dsource-header -Dforce_libcpp -DHXCPP_M64  --app-version="4.0.0-${{ github.run_id}}"
        - name: Make IPA
           runner.os == 'macOS'
          run: |
            brew install ldid
            cd export/release/ios/build/Release-iphoneos/PsychEngine.app
            ldid -S../../../PsychEngine/PsychEngine.entitlements PsychEngine
            cd ..
            mkdir Payload
            mv PsychEngine.app Payload
            zip -r PsychEngine.ipa Payload
        - name: Publish Artifact
          uses: actions/upload-artifact@v4
          with:
            name: iOSBuild
            path: "export/release/ios/build/Release-iphoneos/PsychEngine.ipa"
  release:
    if: github.ref_type == 'tag'
    needs:
      - buildAndroid
      - buildiOS
      
    runs-on: ubuntu-latest

    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: v${{ github.ref_name }}
        draft: true
        prerelease: false

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

    - name: Zip artifacts
      run: |
        zip -r androidBuild androidBuild/
        zip -r /home/runner/PsychEngine-iOS.zip ${{ github.workspace }}/PsychEngine.ipa


    - name: Upload Android build to the release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: androidBuild.zip
        asset_name: androidBuild.zip
        asset_content_type: application/zip

    - name: Upload iOS build to the release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: iOSBuild.zip
        asset_name: iOSBuild.zip
        asset_content_type: application/zip
